# Generated by Django 3.0.7 on 2020-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200617_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogapppost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
