# Generated by Django 3.0.7 on 2020-06-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogapppost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogapppost',
            name='views',
        ),
    ]
