# Generated by Django 3.0.7 on 2020-06-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacthtmldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=332)),
                ('email', models.EmailField(default='', max_length=354)),
                ('phone', models.CharField(default='', max_length=343)),
                ('content', models.CharField(default='', max_length=4376)),
            ],
        ),
    ]
