# Generated by Django 3.0.7 on 2020-06-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacthtmldata',
            old_name='content',
            new_name='desc',
        ),
    ]
