# Generated by Django 3.0.7 on 2020-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200606_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthtmldata',
            name='desc',
            field=models.TextField(max_length=3467),
        ),
    ]
