# Generated by Django 3.0.7 on 2020-06-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200606_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthtmldata',
            name='desc',
            field=models.TextField(default='hey xyz here', max_length=3467),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='email',
            field=models.EmailField(default='xyz123@gmail.com', max_length=354),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='name',
            field=models.CharField(default='xyz', max_length=332),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='phone',
            field=models.CharField(default='123456789', max_length=343),
        ),
    ]
