# Generated by Django 3.0.7 on 2020-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200606_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthtmldata',
            name='desc',
            field=models.TextField(default='', max_length=3467),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='email',
            field=models.EmailField(default='', max_length=354),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='name',
            field=models.CharField(default='', max_length=332),
        ),
        migrations.AlterField(
            model_name='contacthtmldata',
            name='phone',
            field=models.CharField(default='', max_length=343),
        ),
    ]
